#!/bin/bash

echo
echo
echo ---------------------
echo newDocument /document
echo ---------------------

curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d @document.json http://localhost:5000/document

echo
echo
echo ----------------------
echo editDocument /document
echo ----------------------

curl -v -H "Accept: application/json" -H "Content-type: application/json" -X PUT -d @update_document.json http://localhost:5000/document

echo
echo
echo ------------------------
echo deleteDocument /document
echo ------------------------

curl -v -H "Accept: application/json" -H "Content-type: application/json" -X DELETE -d @delete_document.json http://localhost:5000/document
