
/*
  Update country comments.
*/


BEGIN;
-- USA
UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>Estados Unidos ocupa el primer puesto del Índice Elcano de Presencia Global en todos los años para los que se calcula y en todas las variables que lo componen, con las excepciones de energía, manufacturas, tecnología y turismo. También presenta, de los 120 países, las mayores cuotas de presencia en todas las dimensiones –20,5% en la económica; 28,2% en la militar; y 21,9% en la blanda–. Por otro lado, a diferencia de lo que ocurre en otros países desarrollados, la dimensión militar define en buena medida la proyección exterior de Estados Unidos, con una contribución de 26,1% en 2018.</p><p>A pesar de esta hegemonía, Estados Unidos pierde presencia global relativa en comparación con el resto de países, –26,5% de cuota de presencia global en 1990 frente a un 22,6% en 2018–. En un periodo de surgimiento de nuevos actores globales, diversas economías emergentes (particularmente petroleras o asiáticas) cosechan ganancias de cuota que reducen el protagonismo estadounidense. No obstante, en los últimos años y coincidiendo con la desaceleración del proceso de globalización, Estados Unidos recupera algo de su cuota de presencia inicial.</p>'
 WHERE code='US' AND language='es';

UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>US tops the Elcano Global Presence Index in all years and variables, with the exception of energy, manufactures, technology and tourism. Also, of all 120 countries, it records the highest share of presence in all dimensions: 20.5% in the economic domain, 28.2% in the military and 21.9% in soft presence. Moreover, unlike other developed countries, its military dimension strongly defines its index value, with a contribution at 26.1% in 2018.</p>
 <p>Despite its hegemony, the US loses relative global presence when compared with other countries: from a 26.5% share of global presence in 1990 to 22.6% in 2018. In a period of emergence of new global players, several economies (particularly oil producers or Asian countries) reap gains of share that reduce the American role. Nevertheless, more recently and coinciding with the slowing down of the globalization process, the US recovers some of its initial global presence share.  </p>'
 WHERE code='US' AND language='en';

-- UK
UPDATE iepg_data_redux.iepg_comment
SET comment='<p>La presencia global de Reino Unido aumenta constantemente desde 1990, lo que sitúa al país en la segunda posición del ranking entre 2000 y 2012; año en el que cede este puesto a China. Desde entonces, y a pesar de la ralentización de su proyección exterior, fruto de la crisis, mantuvo la tercera posición hasta 2018, cuando es adelantado por Alemania.</p><p>La proyección de Reino Unido hacia el resto del mundo destaca por el elevado peso de la dimensión blanda, ocupando los primeros puestos en todos los indicadores de esta dimensión y siendo el país europeo con mayor presencia blanda en el mundo. El Reino Unido destaca además en algunos indicadores de presencia económica, particularmente en las exportaciones de servicios y en la inversión –téngase en cuenta la importancia de los servicios bancarios, seguros, consultoría y asesoría, así como su función de hub financiero–.</p><p>Dentro del espacio comunitario, en 2018, Reino Unido mantiene la segunda posición del ranking de presencia europea, que calcula la proyección exterior en el espacio europeo. La brecha respecto a Alemania, primero en esta clasificación, persiste, mientras que Francia se mantiene todavía lejos: Reino Unido registró en 2018 una valor de presencia europea de 607 puntos, frente a los 770 de Alemania y los 431 de Francia. Esto podría ser signo del fortalecimiento de relaciones económicas extracomunitarias del Reino Unido en un contexto de menor crecimiento en Europa. En este contexto europeo, el perfil blando de la proyección exterior británica es aún mayor (73% de la presencia europea de Reino Unido se explica con su dimensión blanda).</p>'
WHERE code='GB' AND language='es';

UPDATE iepg_data_redux.iepg_comment
SET comment='<p>The United Kingdom’s global presence has steadily increased since 1990. The country held the 2nd position in the world ranking between 2000 and 2012. It was then surpassed by China. Despite years of slowdown in its external projection as a result of the crisis, the United Kingdom has remained in the 3rd position until 2018, when it is surpassed by Germany.</p><p>The projection of the United Kingdom towards the rest of the world stands on the soft dimension. It occupies the first position in all the indicators of this dimension and is the European country with the highest soft presence record. It is also prominent in some economic indicators such as the investment stock or services exports. In this sense, it is worth noting the importance of banking, insurance and consultancy, and advisory services as well as its role as a financial hub.</p><p>In 2018 and within the European Union, the United Kingdom ranks 2nd in the Elcano European Presence Index. The gap with Germany, which tops this ranking, remains, while it still leaves France further behind. The United Kingdom registered in 2018 a European presence value of 607 points, while Germany recorded 770 and France 431. That could be a symptom of the United Kingdom’s strategy of deepening its extra-European Union economic relations in a context of slow-growing Europe. In this European context, the soft profile of the British external projection is even stronger (73% of the European presence of the United Kingdom corresponds to the soft dimension).</p>'
WHERE code='GB' AND language='en';

-- Rusia
UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>La evolución de la presencia global de Rusia puede dividirse en dos periodos. El primero, que abarca la década de los 90, se caracteriza por una drástica reducción del valor del Índice tras la caída del bloque soviético, con un sustancial descenso de presencia militar, y en menor medida, en la blanda. Así, en 1990 la dimensión militar explicaba de manera abrumadora la presencia global de la entonces Unión Soviética, con un peso del 77,9% en la proyección exterior total.</p><p>En el segundo periodo, que se inicia en 2000, comienza un proceso de recuperación de presencia rusa apoyado principalmente en su dimensión económica. Dicha recuperación, sin embargo, no permite alcanzar los niveles iniciales de proyección exterior.</p><p>Rusia se sitúa, desde 2015, séptimo en el ranking de presencia global. Sigue destacando la dimensión militar, así como las exportaciones energéticas, dada su condición de primer exportador mundial de gas y segundo de petróleo. La dimensión blanda no es tan relevante, aunque el país destaque en deportes (debido a su éxito en el medallero olímpico), información o migraciones.</p>'
 WHERE code='RU' AND language='es';

UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>The evolution of Russia’s global presence can be divided into two periods. The first, during the 1990s, was characterized by a drastic reduction in its Index value following the fall of the Soviet bloc; with a substantial decrease in Russia’s military presence and, to a lesser extent, the soft dimension. In 1990, the military dimension largely underpinned the Soviet Union’s global presence, with a weight of 77.9% in its total value.</p><p>In the second period, from 2000 onwards, there has been a steady process of recovery in Russia’s global presence, primarily supported by the economic dimension. However, Russia has been unable to return to the world projection levels of the Soviet era.</p><p>Russia ranks 7th in the global presence ranking since 2015. It still outstands in the military dimension, as well as in energy exports, given that it is the world first exporter of gas, and the second of oil. The soft dimension is less relevant, despite Russia’s performance in sports –given its records in the Olympic medal table–, information and migrations.</p>'
 WHERE code='RU' AND language='en';

-- France
UPDATE iepg_data_redux.iepg_comment
SET comment='<p>Francia se enfrenta a una pérdida relativa de relevancia en la escena internacional. Ello se refleja en su posición en el ranking de presencia global, 4ª desde los 90, 5ª desde 2012 y 6ª en el 2018. Mantiene un perfil similar al de otras economías europeas, con una fuerte presencia blanda sobre todo en turismo, –siendo la primera potencia turística a nivel mundial–, cultura o cooperación al desarrollo.</p><p>Es el 4º país en presencia en el espacio europeo, medida con el Índice Elcano de Presencia Europea, tras haber perdido el tercer puesto que ahora ocupa Países Bajos.</p>'
WHERE code='FR' AND language='es';

UPDATE iepg_data_redux.iepg_comment
SET comment='<p>France faces a relative loss of relevance in the international scene. This is reflected in its ranking position: 4th since the 90s, 5th since 2012 and the sixth in 2018. France maintains a profile similar to those of other European economies, with a strong soft presence mainly in tourism –being the leading worldwide tourist destination– culture or development cooperation.</p><p>France is 4th in the European sphere, when measured with the Elcano European Presence Index, after losing the 3rd position which is now held by the Netherlands.</p>'
WHERE code='FR' AND language='en';

-- Spain
UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>España ocupa la 12ª posición en el Índice Elcano de Presencia Global, perdiendo en el último año el 11º puesto que ahora ocupa India. Por dimensiones, su fortaleza sigue estando en la dimensión blanda (10ª posición), además de la económica (en la que ocupa también la 10ª posición). En el plano militar, el papel internacional de España es más pasivo (15ª posición).</p><p>En la década de los 90 aumentó notablemente su presencia global, debido al crecimiento tanto de la dimensión económica y, sobre todo, de la blanda. Destaca la variable de turismo, siendo el 2º país con mayor número de visitantes extranjeros. La dimensión económica se ve afectada por la crisis de finales de los 2000, aunque recientemente se produce una recuperación de los servicios, que se explica con el sector turístico.</p><p>España es 6ª en el ranking del Índice Elcano de Presencia Europea. Destaca en ese ámbito la dimensión blanda, con protagonismo de las migraciones, el turismo o publicaciones científicas.</p>'
 WHERE code='ES' AND language='es';

UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>Spain is 12th in the Elcano Global Presence Index. It has lost the 11th position, which is now held by India, over last year. By dimensions, its main strength is in the soft dimension, (10th place), as well as in the economic (also 10th place). However, in the military sphere (15th), Spain’s international role is more passive.</p><p>Spain’s global presence increased significantly during the 90s; a trend supported by the economic dimension and, mainly, by its soft presence. Tourism stands out, being the 2nd world destination. The economic dimension was affected by the late 2000s crisis. However, there has been a recent recovery of the services variable, due to the performance of tourism.</p><p>Spain ranks 6th in the Elcano European Presence Index. It outstands in the soft dimension, with a leading role in migration, tourism or scientific publications.</p>'
 WHERE code='ES' AND language='en';

-- India
UPDATE iepg_data_redux.iepg_comment
SET comment='<p>India ocupa la 11ª poción del ranking del Índice Elcano de Presencia Global, superando a España en 2018. Se trata de un puesto relativamente bajo en comparación con su tamaño en términos de PIB (sexto puesto en la clasificación mundial) y también bajo respecto a su tamaño en términos de población (segundo puesto).<p>Estos datos se explican con el modelo de desarrollo de India que, a diferencia del de China, ha estado orientado a la economía interna. Quizá por ello, dentro de su proyección exterior, tiene tanta relevancia la dimensión militar en comparación con lo que ocurre en el conjunto de la región asiática –29% de contribución de esta dimensión a su presencia global en 2018, frente a un 12% para el conjunto de Asia y Pacífico–.</p><p>No obstante, en los últimos años, parece estar dándose un cambio de tendencia. India registra importantes crecimientos de presencia económica –con mayor protagonismo de los servicios, seguidos por manufacturas y bienes primarios–, así como en algunos indicadores de la dimensión blanda –cultura, ciencia y tecnología–. Ello le ha permitido ganar cuota de presencia global, adelantando tanto a España como a Corea del Sur, y mostrando el enorme potencial de crecimiento de proyección exterior de uno de los países más grandes del mundo.</p>'
WHERE code='IN' AND language='es';

UPDATE iepg_data_redux.iepg_comment
SET comment='<p>India occupies the 11th position in the Elcano Global Presence Index, overtaking Spain in 2018. This position is relatively low in comparison with its size in terms of GDP (sixth place in the world ranking) and specially with respect to its size in terms of population (second place). These data are consistent with the development model of India, which, unlike China, has been oriented mainly inward-oriented. Perhaps for this reason, within its external projection, the military dimension is so relevant in comparison with that of other Asian countries –29% of its global presence in 2018, 12% for the whole Asia and the Pacific region–.</p><p>However, this trend has changed recently. India records an important growth of economic presence –with prominence of services exports, followed by manufactures and primary goods– as well as in some indicators of the soft dimension –culture, science and technology–. This has allowed India to gain global presence share since 2010, ahead of Spain and South Korea, and showing the enormous potential of growth of the external projection of one of the largest countries in the world.</p>'
WHERE code='IN' AND language='en';

-- European Union
UPDATE iepg_data_redux.iepg_comment
SET comment='<p>Si considerásemos a la Unión Europea un único país, ocuparía en 2018 el primer puesto en la clasificación de Presencia Global, con un registro similar al de Estados Unidos.  Obtendría el mayor valor de presencia económica –con relevancia de la inversión en el exterior y las exportaciones de servicios– y también el mayor registro de presencia blanda –turismo, deportes y cooperación al desarrollo–, siendo superado por Estados Unidos tan sólo en la clasificación de presencia militar.</p><p>La crisis económica, con especial impacto dentro del espacio comunitario, ha condicionado la presencia de la Unión Europea en el resto del mundo. Por un lado, dentro de la dimensión económica, registra una tendencia de pérdida de presencia hasta 2013, fundamentalmente debida al descenso de exportaciones de manufacturas y de inversión en el exterior –en parte consecuencia la depreciación del euro frente a otras monedas–. Por otro lado, se da una ralentización del crecimiento de su presencia blanda, afectada entre otras cosas por la reducción los flujos de cooperación internacional, así como al número de inmigrantes recibidos.</p><p>No obstante, tanto la Unión Europea como Estados Unidos mantienen unos elevados niveles de presencia global, que les sitúa por el momento a mucha distancia de China, que ocuparía el tercer lugar.</p>'
WHERE code='XBEU' AND language='es';

UPDATE iepg_data_redux.iepg_comment
SET comment='<p>If the European Union were to be considered a single country, it would occupy the first place in the Global Presence ranking in 2018, with a record similar to that of the United States.
The European Union would have the greatest value of economic presence –with relevance of foreign investment and exports of services– and also the greatest record of soft presence –tourism, sports or development cooperation-–, being surpassed by the United States only in the classification of military presence.</p><p>The economic crisis, which has especially hit the European Union, has had an impact on its presence in the rest of the world. On the one hand, within the economic dimension, there is a trend of loss of presence until 2013, mainly due to the decline in exports of manufactures and foreign investment –in part due to the depreciation of the euro against other currencies–.</p><p>On the other hand, there is a slowdown in the growth of its soft presence, affected among other things by the reduction of international cooperation flows, as well as the number of immigrants received.</p>
<p>However, both the European Union and the United States maintain high levels of global presence, which locates them still far from China, which would occupy the 3rd place.</p>'
WHERE code='XBEU' AND language='en';

-- China
UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>El notable ascenso del gigante asiático en las últimas décadas tiene su reflejo en la clasificación del Índice Elcano de Presencia Global, donde escala ocho posiciones desde 1990. Este crecimiento se da en paralelo al registrado en términos de PIB, otorgando el protagonismo del auge chino a la dimensión económica –en 1990 ocupaba el 17º lugar frente al 2º en 2018 en el ranking de presencia económica–, impulsado por el crecimiento de las exportaciones manufactureras, pero también de bienes primarios, servicios e inversiones. Por ello, la naturaleza de su presencia global es principalmente económica, con un peso del 54,3% sobre el valor índice en 2018.</p><p>Sin embargo, recientemente registra también aumentos sustanciales de presencia blanda, con un valor en 2018 que es 26 veces mayor que en 1990 –frente a las 14 veces que ha aumentado su presencia económica–. El comportamiento de la presencia blanda se explica con el de indicadores como información, tecnología o ciencia, y muestra una posible tendencia de modificación de las bases de su presencia, a la vez que se consolida su posición global. Esto se evidencia con el incremento de cuota de presencia –un 8,0% en 2018 frente al 1,8% de 1990– que, si bien se sitúa todavía lejos de los registros estadounidenses, le ha permitido adelantar a potencias europeas como Francia, Reino Unido y Alemania, y situarse en el segundo puesto del ranking de presencia global.</p>'
 WHERE code='CN' AND language='es';

UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>China’s remarkable rise in recent decades is reflected in its classification in the Elcano Global Presence Index, where it has upscaled 8 positions since 1990. It has also grown in terms of GDP, with a prime role played by the economic presence –in 1990 China ranked 17th and in 2018 the country holds 2nd place in this dimension– mainly driven by the export of manufactures, but also by primary goods, services and investments. Hence, the nature of its global presence is mainly economic, accounting for 54.3% of its index value in 2018.</p><p>However, more recently China has also registered substantial increases of soft presence, with a record in this dimension 26 times higher in 2018 than in 1990 –its economic presence has been multiplied by 14 times in the same period– pushed by the increase in indicators such as information, technology or science; and reflecting a possible change of the nature of China’s presence over the world. This is also evident in terms of quota, at 8.0% in 2018 compared with 1.8% in 1990. Although still far from the US, China has recently overtaken France, the United Kingdom and Germany.</p>'
 WHERE code='CN' AND language='en';


-- Germany
UPDATE iepg_data_redux.iepg_comment
SET comment='<p>Desde mediados de los 90, tras la reunificación y la caída del bloque soviético, Alemania registró un aumento continuado de presencia exterior, apoyada fundamentalmente en su proyección económica, que aporta más del 69% de su presencia global, y en donde, a excepción de las exportaciones energéticas, ocupa un lugar muy destacado en todas las variables a nivel mundial (entre las cinco primeras posiciones). La recuperación en los últimos años del ritmo de crecimiento de su presencia global le ha permitido superar a Reino Unido, y situarse en la tercera posición de la clasificación mundial por detrás de China y Estados Unidos. Una posición que había perdido desde 2013, consecuencia del impacto de la crisis en el territorio europeo, y por tanto en la proyección económica de Alemania.</p><p>Dentro de la Unión Europea, Alemania mantiene su hegemonía a pesar de la contracción de la demanda de los socios comunitarios, con descensos de las exportaciones de manufacturas alemanas con destino al mercado europeo. La presencia alemana en Europa tiene un carácter fundamentalmente económico, destacando el stock de inversión y las exportaciones de manufacturas y bienes primarios.</p>'
WHERE code='DE' AND language='es';

UPDATE iepg_data_redux.iepg_comment
SET comment='<p>Since the mid-1990s and following the fall of the Soviet Union and its reunification, Germany has been recording a steady growth in its economic presence, a dimension that provides over 69% of its external projection and where it holds a prominent place in all variables –except energy exports–. The recovery from the crisis, in recent years, of the trend of growth of its global presence has allowed Germany to surpass the United Kingdom, thus recovering the 3rd position –behind China and the United States– lost since 2013.</p><p>Within the European Union, Germany has maintained its hegemony, despite the decreasing demand from its European Union partners. Germany’s European presence has an essentially economic nature, based on its investment stock and manufacturing and primary goods exports.</p>'
WHERE code='DE' AND language='en';

 -- Japan
 UPDATE iepg_data_redux.iepg_comment
  SET comment='<p>Japón ocupa el 5º lugar en la clasificación de presencia global, adelantando dos posiciones con respecto a 2013, a pesar del letargo económico tras la crisis de los 90. Aun manteniendo el tercer PIB más elevado a nivel mundial, en términos de proyección exterior, la economía nipona ha sufrido una importante pérdida de relevancia económica, pasando de ocupar el tercer puesto en esta dimensión en 1990, al quinto en 2018.</p><p>No obstante, en los tres últimos años, Japón recupera presencia en el resto del mundo, debido a su proyección económica –donde destaca el stock de inversión en el exterior– hasta adelantar a Francia en esta dimensión. También aumenta la dimensión militar, que a pesar de la desmilitarización tras la Segunda Guerra Mundial, contribuye crecientemente a la presencia japonesa –21,3% en 2018– y más que en otras economías desarrolladas.</p><p>Cae la presencia blanda tanto en términos absolutos como relativos –en 1990 registraba 521 puntos, 37% de su proyección exterior ese año; en 2018, 373 puntos y 22% de su proyección exterior– aunque se mantenga en niveles elevados –5º puesto mundial en esta dimensión en 2018, sustentados en las variables de tecnología, ciencia y cooperación al desarrollo–.</p>'
  WHERE code='JP' AND language='es';

 UPDATE iepg_data_redux.iepg_comment
  SET comment='<p>Japan ranks 5th in the global presence ranking –two more positions than in 2013– despite its economic lethargy following the crisis of the 1990s. Although it retains the 3rd largest GDP, in terms of external projection Japan has suffered a significant decline in economic presence, falling from the 3rd position in 1990 to 5th in 2018.</p><p>In the last three years, Japan increases its economic projection –mainly due to its stock of foreign investment abroad–, overtaking France. The military dimension also grows –up to a contribution of 21.3% in 2018– and is higher than in other developed countries, despite the demilitarization following the World War II.</p><p>The soft dimension falls both in absolute and relative terms –in 1990 it was at 521 points or 37% of its external projection; in 2018, at 373 points and 22%–, although maintaining high records –5th position worldwide in 2018 based on indicators such as technology, science and development cooperation.</p>'
  WHERE code='JP' AND language='en';

 -- Italy
 UPDATE iepg_data_redux.iepg_comment
  SET comment='<p>Italia se mantiene, desde 2010, en el 10º puesto del ranking –frente al 7º puesto ocupado en 1990–. Esta tendencia se debe a la ralentización del crecimiento de su presencia económica, que tiene un escaso crecimiento desde los 90 en comparación con otros países del entorno. No obstante, continúa siendo uno de los países más industrializados, por lo que tiene relevancia dentro de las exportaciones de manufacturas e inversiones en el exterior. Al igual que ocurre con otras potencias europeas, mantiene registros elevados en la dimensión blanda –apoyada en tecnología, cooperación al desarrollo, ciencia y turismo–.</p><p>Por el contrario, dentro del espacio europeo su presencia es fundamentalmente blanda –estando entre los cinco primeros puestos en turismo, migraciones, deportes, tecnología y ciencia, y entre los diez primeros en información y educación– y ha sido precisamente esta dimensión la que mayores crecimientos había venido registrando.</p>'
  WHERE code='IT' AND language='es';

 UPDATE iepg_data_redux.iepg_comment
  SET comment='<p>Italy holds the 10th place in the Elcano Global Presence Index ranking since 2010 –7th position in 1990–. This trend is due to the slower growth of its economic presence, which has registered a low increase compared to other neighboring countries. However, Italy is still one of the most industrialized countries, so its presence is fundamentally economic, supported by manufactured exports and investments. Similarly to other European countries, Italy has a high score in the soft dimension –mainly because of technology, science, tourism and international cooperation–.</p><p>Within the European Union, Italy’s presence is of a soft nature. This dimension has registered the greatest growth –climbing positions up to being one of the top five European countries in tourism, migration, sports, technology and science and one of the top 10 ranks in education and information–.</p>'
  WHERE code='IT' AND language='en';

  -- Canada
  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Canadá ocupa en 2018 el 8º puesto del ranking de presencia global, manteniéndose en los principales puestos a pesar de la reducción relativa de su peso económico en el mundo –pierde cuatro puestos en la clasificación mundial de PIB desde 1990– y del auge de China. Mantiene un perfil de presencia fundamentalmente económico –74% de su presencia global en 2018– con protagonismo de las inversiones en el exterior, pero con contribuciones relevantes de otros indicadores como bienes primarios o energía, dada su condición de cuarto productor de gas y petróleo a nivel mundial. Aunque la dimensión blanda es menos relevante en su proyección exterior, ocupa posiciones elevadas en cultura (3ª posición), educación, ciencia y migraciones (7ª posición).</p>'
   WHERE code='CA' AND language='es';

  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Canada occupies the 8th place in the global presence ranking in 2018, remaining in the main positions despite its loss of economic weight –down four positions since 1990 in the GDP ranking– and despite the rise of China. It maintains a strong economic profile –74% of its global presence in 2018– with a leading role in foreign investments abroad, and also with relevant contributions from other indicators such as primary goods or energy, given its condition of 4th largest gas and oil producer. Although the soft dimension is less determinant, Canada occupies high positions in some indicators of this dimension, such as culture (3rd position worldwide), education, science and migration (7th).</p>'
   WHERE code='CA' AND language='en';

COMMIT;
