
/*
  Update country comments.
*/


BEGIN;
-- USA
UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>Desde la caída del bloque soviético, la supremacía estadounidense tiene su visibilidad en distintas esferas del Índice Elcano de Presencia Global. En primer lugar, Estados Unidos ocupa el primer puesto de la clasificación en todos los años para los que se calcula y en todas las variables que lo componen, a excepción de las exportaciones de energía, manufacturas y turismo. En segundo lugar, registra las mayores cuotas de presencia en todas las dimensiones –20% en la económica; 28% en la militar; y 24% en la blanda–. Por otro lado, a diferencia del resto de países desarrollados, la dimensión militar mantiene una elevada contribución al valor del Índice –21,6% en 2017–. </p><p>Sin embargo, y al tiempo que mantiene su hegemonía, registra una tendencia de pérdida de presencia en términos relativos y en comparación con el resto de países, –26,0% de cuota de presencia global en 1990 frente a un 22,5% en 2017–. En un periodo de surgimiento de nuevos actores globales, diversas economías emergentes cosechan ganancias de cuota que reducen el protagonismo estadounidense, donde destaca el auge de países petroleros y asiáticos. Sin embargo, la desaceleración del proceso de globalización en los últimos años ha producido una ligera reconcentración de la presencia global, permitiendo a EEUU mantener su cuota de presencia en los últimos años.</p><p>Esta tendencia se debe fundamentalmente a la dimensión económica del Índice, donde a pesar de ser el principal motor de la globalización, y por tanto la dimensión en la que Estados Unidos registra mayores aumentos de presencia –especialmente en las exportaciones de servicios y <i>stock</i> de inversión–, reduce su cuota en casi cuatro puntos porcentuales entre 1990 y 2012. La recuperación desde entonces de su cuota económica ha permitido compensar las pérdidas en la dimensión blanda. Al mismo tiempo, la tendencia general a la desmilitarización de la presencia de los países en el mundo permite a Estados Unidos mantener su hegemonía militar a pesar de la reducción del número de unidades desplegadas.</p>'
 WHERE code='US' AND language='es';

-- South Corea
UPDATE iepg_data_redux.iepg_comment
 SET comment=''
 WHERE code='KR' AND language='es';

UPDATE iepg_data_redux.iepg_comment
 SET comment=''
 WHERE code='KR' AND language='en';

-- China
UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>El notable ascenso del gigante asiático en las últimas décadas tiene su reflejo en la clasificación del Índice Elcano de Presencia Global, donde escala nueve posiciones desde 1990. Este crecimiento se da en paralelo al registrado en términos de PIB, otorgando el protagonismo del auge chino a la dimensión económica –en 1990 ocupaba el 17º lugar frente al 2º en 2017 en el ranking de presencia económica–, impulsado por el crecimiento de las exportaciones manufactureras, pero también de bienes primarios y servicios.</p><p>Por ello, la naturaleza de su presencia global es principalmente económica, con un peso del 56,2% sobre el valor índice en 2017. Sin embargo, registra también recientes mejoras sustanciales en variables de la dimensión blanda –en turismo, deportes, ciencia, información y tecnología-, mostrando una posible tendencia de modificación de las bases de su presencia, a la vez que consolida su posición global. Esta consolidación se evidencia con el incremento de cuota de presencia –un 7,6% en 2017 frente al 1,6% de 1990– que, si bien se sitúa todavía lejos de los registros estadounidenses, le ha permitido adelantar a potencias europeas como Francia, Reino Unido y Alemania, y situarse en el segundo puesto del ranking de presencia global.</p>'
 WHERE code='CN' AND language='es';

UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>China’s remarkable rise in recent decades is reflected in its classification in the Elcano Global Presence Index, where it has risen 9 positions since 1990. It has also grown in terms of GDP, with a prime role played by the economic presence –in 1990 China ranked 17th and in 2017 the country holds 2nd place in this dimension– mainly driven by the export of manufactures, but also of primary goods and services. Hence, the nature of its global presence is mainly economic, accounting for 56.2% of the Index’s value in 2016. However, there has been a recent improvement in the soft variables –tourism, sports, science, information and technology–, reflecting a possible change in trend in the nature of China’s presence, while it has consolidated its global position. This is also evident in terms of share, at 7.6% in 2017 compared with 1.6% in 1990. Although still far from the US, China has recently overtaken France, the United Kingdom and Germany.</p>'
 WHERE code='CN' AND language='en';

-- Germany
UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>A pesar del crecimiento de presencia respecto del año anterior, Alemania se mantiene en la cuarta posición del ranking, a la que quedó relegada en 2013, siendo superado en presencia global por China. Desde mediados de los 90, tras la reunificación y la caída del bloque soviético, Alemania registró un aumento continuado de presencia económica, dimensión que más valor le aporta y donde, a excepción de las exportaciones energéticas, ocupa lugar muy destacado en todas las variables a nivel mundial (entre las tres primeras posiciones). Sin embargo, el descenso de presencia registrado en 2013 y el modesto crecimiento de los últimos años, no le han permitido mantener una tercera posición que ocupaba desde el año 2000.</p><p>Dentro de la Unión Europea, Alemania mantiene su hegemonía. A pesar de la contracción de la demanda de los socios comunitarios, con descensos de las exportaciones de manufacturas con destino al mercado europeo, la presencia europea alemana tiene un carácter fundamentalmente económico, destacando el <i>stock</i> de inversión y las exportaciones de manufacturas y bienes primarios. No obstante, en 2015 registra por primera vez una pérdida en términos absolutos de presencia económica dentro de la UE. Dentro de la dimensión blanda, la presencia alemana se caracteriza por apoyarse fundamentalmente en pilares sólidos, como las variables de información, tecnología, ciencia y educación.</p>'
 WHERE code='DE' AND language='es';

UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>Despite the growth of its global presence in absolute terms, Germany remains at 4th place in the global presence ranking -spot to which the country was relegated in 2013-, being overtaken in global presence by China. Since the mid-1990s, and following the fall of the Soviet Union and the reunification, Germany has been recording a steady growth in its economic presence, the dimension that provides the highest contribution to its position and in which it occupies a prominent place in all variables –save energy exports–. The decline of presence in 2013 and the slight recovery over the past years have not allowed Germany to maintain the 3rd position in the global presence ranking (held since the year 2000).</p><p>Within the European Union, Germany has maintained its hegemony. Despite the decreasing demand from its European Union partners, Germany’s European presence has an essentially economic nature, based on its investment stock and manufacturing and primary goods exports. Nevertheless, in 2015 Germany registers for the first time an economic presence loss in absolute terms within the EU. Furthermore, within the soft dimension, its presence is based on the solid pillars of information, technology and science.</p>'
 WHERE code='DE' AND language='en';

-- UK
UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>La presencia global de Reino Unido ha registrado un constante aumento desde 1990, lo que le ha permitido ascender posiciones en la clasificación, superando a Francia y a Alemania, y manteniendo la segunda posición del ranking mundial desde el año 2000. En 2014 es superado por China, tras años de ralentización de la proyección exterior británica fruto de la crisis y del crecimiento sostenido chino, manteniéndose desde entonces como el tercer país del mundo con mayor presencia global.</p><p>La proyección de Reino Unido hacia el resto del mundo destaca por el elevado peso de la dimensión blanda, ocupando los primeros puestos en todos los indicadores de esta dimensión -a excepción del turismo- y siendo el país europeo con mayor presencia blanda en el mundo, lo que le ha permitido mantener su cuota global a pesar del ascenso de países emergentes. La posición relativa internacional de Reino Unido se sostiene, además, por su gran importancia en algunos indicadores de presencia económica, particularmente en las exportaciones de servicios e inversión –téngase en cuenta la importancia de los servicios bancarios, seguros, consultoría y asesoría, así como su función de <i>hub</i> financiero-. El decrecimiento del valor absoluto y relativo al que asiste Reino Unido en los últimos años responde a la reducción de su presencia económica, consecuencia directa de la crisis económica, mientras su presencia blanda permanece estable.</p><p>Dentro del espacio comunitario, Reino Unido mantiene la segunda posición en 2017 del ranking de presencia europea. No obstante, la brecha respecto a Alemania persiste, mientras que Francia se mantiene todavía lejos. Esto podría ser signo del fortalecimiento de relaciones económicas extracomunitarias del Reino Unido en un contexto de menor crecimiento en Europa, mientras que el perfil blando de la proyección exterior británica se agudiza todavía dentro de la Unión Europea (79% de la presencia europea de Reino Unido corresponde a la dimensión blanda).</p>'
 WHERE code='GB' AND language='es';

UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>The United Kingdom’s global presence has steadily increased since 1990, climbing up the ranking to outstrip France and Germany, and holding the 2nd position in the world ranking since 2000. In 2014 it was surpassed by China, after years of slowdown in the British external projection as a result of the crisis, remaining since then the 3rd position in the global presence ranking.</p><p>The projection of the United Kingdom towards the rest of the world stands on the soft dimension, occupying the first positions in all the indicators of this dimension -with the exception of tourism- and being the European country with the highest soft presence record, allowing it to keep its global share despite the rise of emerging countries. However, its increase of presence has been sustained mainly by its economic dimension with prominence of investment stock and services exports –based on the importance of banking, insurance and consultancy, and advisory services as well as its role as a financial hub–. The recent contraction of the United Kingdom’s absolute and relative values of presence is due to the reduction of its economic presence, a direct consequence of the economic crisis, while its soft presence remains stable.</p><p>Within the European Union, the United Kingdom keeps the 2nd place in 2017 in European presence. Accordingly, the gap with respect Germany has increased, while it still leaves France further behind. That could be a symptom of the United Kingdom’s strategy of deepening its extra-European Union economic relations in a context of slow-growing Europe, while the soft profile of the British external projection is still more relevant within the European Union (79% of the European presence of the United Kingdom corresponds to the soft dimension).</p>'
 WHERE code='GB' AND language='en';

-- Rusia
UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>La evolución de la presencia global de Rusia puede dividirse en dos periodos. El primero, que abarcaría la década de los 90, caracterizado por una drástica reducción del valor del Índice tras la caída del bloque soviético, con un sustancial descenso de presencia militar, y en menor medida, en la blanda. Así, en 1990 la dimensión militar sostenía de manera abrumadora la presencia global de la entonces Unión Soviética, con un peso del 76% del valor total. En el segundo periodo, a partir del año 2000, comienza un proceso de recuperación de presencia en el mundo apoyado principalmente en su dimensión económica que, sin embargo, no le permite alcanzar los mismos niveles que obtenía durante la época soviética. Destaca el elevado peso de la dimensión militar en su proyección exterior, así como la relevancia de las exportaciones energéticas, dada su condición de primer exportador de gas y segundo de petróleo a nivel mundial. La dimensión blanda es menos protagonista de la proyección rusa, aunque ocupa posiciones relevantes en algunos indicadores de esta dimensión como deportes (debido a su éxito en el medallero olímpico), información y migraciones.</p>'
 WHERE code='RU' AND language='es';

UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>The evolution of Russia’s global presence can be divided into two periods. The first, during the 1990s, was characterized by a drastic reduction in its Index value following the fall of the Soviet bloc, with a substantial decrease in military presence. In 1990 the military dimension largely underpinned the Soviet Union’s global presence, with a weight of 76% in its total value. In the second period, from 2000 onwards, there has been a steady process of recovery in its global presence, primarily supported by the economic dimension, although Russia has been unable to return to the levels of the Soviet era until 2012. It also highlights the weight of the military dimension in its external projection, as well as the relevance of energy exports, given its leading role as exporter of gas and the second one of oil worldwide. The soft dimension is less relevant of the Russian external projection, although it gets good records in some soft indicators as sports –given its success in the Olympic medal table–, information and migrations.</p>'
 WHERE code='RU' AND language='en';

-- France
UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>A pesar del aumento continuado de presencia global, Francia se enfrenta a una pérdida progresiva de relevancia en la escena internacional. Ello se refleja en su posición en el ranking de presencia global, la cuarta desde los 90 y 5ª desde 2012. Mantiene un perfil similar al de otras economías europeas, esto es, elevados registros de presencia blanda –sobre todo en turismo, siendo la primera potencia turística a nivel mundial-, cultura o cooperación al desarrollo; al mismo tiempo, su dimensión económica crece, aunque en menor cuantía y con ciertas variaciones, debidas en parte al impacto de la crisis.</p><p>En términos europeos, se sitúa como la cuarta economía con mayor presencia dentro del espacio comunitario tras una pérdida de presencia en términos absolutos el último año, cediendo el tercer puesto a Países Bajos.</p>'
 WHERE code='FR' AND language='es';

UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>Despite its continued increase in global presence, France faces a progressive loss of relevance in the international scene. This is reflected in the decline in its share of presence and its loss of position in the ranking, holding on to the 4th position since the 90s and the 5th since 2012. France maintains a profile that is similar to those of other European economies, with a high soft presence –being the leading worldwide tourist destination– culture o cooperation, while the economic dimension grows, yet in short amount and with certain variations, due to the European economic crisis.</p><p>In European terms, France is the 4th country with more presence in the EU, after a loss of presence in absolute terms last year, yielding the third place to the Netherlands.</p>'
 WHERE code='FR' AND language='en';

-- Japan
UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>Japón ocupa el 6º lugar en la clasificación, adelantando una posición con respecto a 2013 y a pesar del letargo económico tras la crisis de los 90 que le ha hecho registrar, por lo general, menores tasas de crecimiento de presencia que países que le acompañan en los principales puestos. A pesar de mantener el tercer PIB más elevado a nivel mundial, en términos de presencia, la economía nipona ha sufrido una importante pérdida de relevancia económica, pasando de ocupar el tercer puesto en esta dimensión en 1990, al sexto hasta 2016. En 2017 Japón aumenta su proyección económica –fundamentalmente por el aumento de <i>stock</i> de inversión en el exterior–, pasando a ocupar el cuarto lugar por delante de Francia en el ranking de presencia económica.</p><p>Se observa lo mismo en términos de cuota de presencia económica, que pasa de un 7,8% en los 90 a un 5% en 2017, con una tendencia de leve crecimiento en los últimos años. No obstante, mantiene al mismo tiempo elevados registros de presencia blanda –6º puesto mundial en esta dimensión en 2017–, sustentados en las variables de tecnología, ciencia y cooperación al desarrollo. Cabe añadir que, a pesar de la desmilitarización sufrida tras la Segunda Guerra Mundial, la dimensión militar mantiene una contribución estable a la presencia japonesa -en torno al 15% los últimos años– y superior a otras economías desarrolladas.</p>'
 WHERE code='JP' AND language='es';

UPDATE iepg_data_redux.iepg_comment
 SET comment='<p>Japan ranks 6th despite its economic lethargy following the crisis of the 1990s, which led to it recording lower growth rates in its presence than other major countries. Despite retaining the 3rd largest GDP, Japan has suffered a significant decline in economic presence, falling from the 3rd position in 1990 to 6th since 2016.</p><p>In 2017, Japan increases its economic projection to the world - mainly due to the increase in stock of foreign investment abroad -, going up to the 4th position in the ranking of economic presence overtaking France.</p><p>In terms of economic share, comes down from 7.8% in the 90s to 5% in 2017, with a growing trend in recent years. However, it still has a high score in soft presence –being 6th worldwide– supported by technology, science and cooperation. At the same time, and despite its demilitarization after WWII, the military dimension contributes around 15% to the country’s global presence, higher than for other developed economies.</p>'
 WHERE code='JP' AND language='en';

-- The Netherlands
UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>A pesar del paulatino descenso de los Países Bajos en la clasificación mundial según el PIB, el país se mantiene en puestos elevados del Índice Elcano de Presencia Global. Se trata de una presencia de naturaleza fundamentalmente económica –esta dimensión representa en 2017 el 76% de su presencia global–. A su potencial exportador de bienes primarios se añade, por un lado, su condición de principal productor de gas en la Unión Europea y la posición estratégica del puerto de Rotterdam, y por otro lado, su posición estratégica en el sistema bancario y financiero europeo. Así, buena parte de su elevado registro puede explicarse por su condición de <i>hub</i> exportador e inversor.</p><p>Este perfil se repite en el análisis de su presencia dentro del espacio europeo, donde ocupa el tercer puesto por detrás de Alemania y Reino Unido, habiendo adelantado a Francia el último año.</p>'
   WHERE code='NL' AND language='es';

  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Despite the gradual decline in its world ranking by GDP, the Netherlands retains a high position in the Elcano Global Presence Index. Its economic dimension –which in 2017 accounted for 76% of its total value– continues to be the most important component.</p><p>The importance of the Netherlands as exporter of primary goods is added, on the one hand, to its status as the main gas European producer and the strategic position of the port of Rotterdam and, on the other hand, its strategic position in the European banking and financial system. Thus, much of its position can be explained by its role as an export and investor hub.</p><p>Its profile is replicated in Europe, where The Netherlands has the 3rd highest value after Germany and the United Kingdom, having overtaken France last year.</p>'
   WHERE code='NL' AND language='en';

  -- Canada
  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Canadá ocupa en 2017 el 8º puesto del ranking de presencia global, manteniéndose en los principales puestos a pesar de la reducción relativa de su peso económico en el mundo –pierde cinco puestos en la clasificación mundial de PIB desde 1990– y del auge de China.</p><p>Mantiene un perfil de presencia fundamentalmente económico –68,9% de su presencia global en 2017– con protagonismo de las inversiones en el exterior, pero con contribuciones relevantes de otros indicadores como bienes primarios o energía, dada su condición de cuarto productor de gas y petróleo a nivel mundial (según el informe “BP Statistical Review of World Energy” de 2016).</p><p>Presenta por el contrario un perfil de presencia blando bajo –25% de su presencia global en 2017–, y con un escaso crecimiento en los últimos años.</p>'
   WHERE code='CA' AND language='es';

  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Canada occupies the 8th place in the global presence ranking in 2017, staying in the main positions despite its loss of economic weight –down five positions since 1990– and the rise of China.</p><p>It maintains a profile of presence mainly economic -68.9% of its global presence in 2017- with a leading role of the foreign investments abroad, but also with relevant contributions from other indicators such as primary goods or energy, given its condition of 4th largest gas and oil producer (according to the BP Statistical Review of World Energy of 2016).</p><p>On the contrary, it presents a low profile of soft presence -25% of its global presence in 2017-, and with scant growth in recent years.</p>'
   WHERE code='CA' AND language='en';

  -- Italy
  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>A pesar de perder progresivamente posiciones tanto en términos de cuota de presencia global como de PIB, Italia se mantiene, desde 2010, en el 10º puesto del ranking –frente al 7º puesto ocupado en 1990–. Esta tendencia se debe a la ralentización del crecimiento de su presencia económica, que ha registrado un escaso crecimiento desde los 90 en comparación con otros países del entorno. No obstante, continúa siendo uno de los países más industrializados, por lo que su presencia económica es relevante, apoyada en las exportaciones de manufacturas e inversiones en el exterior. Al igual que ocurre con otras potencias europeas, mantiene registros elevados en la dimensión blanda –apoyada en tecnología, ciencia y turismo–.</p><p>Por el contrario, dentro del espacio europeo su presencia es fundamentalmente blanda –estando entre los cinco primeros puestos en turismo, migraciones, deportes, tecnología y ciencia, y entre los diez primeros en información y educación– y ha sido precisamente esta dimensión la que mayores crecimientos había venido registrando. Sin embargo, desde 2015, registra una pérdida de presencia blanda que le hace descender al 6º puesto del ranking de presencia europea por detrás de Bélgica.</p>'
   WHERE code='IT' AND language='es';

  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Despite its steady loss of both positions and share in terms of Global Presence and GDP, Italy holds the 10th place in the Elcano Global Presence Index ranking since 2010 –7th position in 1990–. This trend is due to the slower growth of its economic presence, which has registered a low growth since then compared to other neighboring countries. However, Italy is still one of the eight most heavily industrialized countries, so its presence is fundamentally economic, supported by manufactured exports –despite a slight decline in 2016- and investments. Similarly to other European countries, Italy has a high score in the soft dimension –mainly because of technology, science and tourism–, where the reduction in international cooperation flows contributed to an unprecedented decline in the Index in absolute terms in 2013.</p><p>Within the European Union, Italy’s presence is of a soft nature. This dimension has registered the greatest grown –climbing positions up to being one of the top five European countries in tourism, migration, sports, technology and science and one of the top ten in education and information–. However, since 2015, it registers a loss of soft presence in the EU which causes the descend to 6th place in the ranking of European presence behind Belgium.</p>'
   WHERE code='IT' AND language='en';

  -- Spain
  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>España mantiene la 11ª posición en el Índice Elcano de Presencia Global, aunque pierda cuota de presencia global en todas sus dimensiones (al igual que otros países de su entorno). Por dimensiones, su fortaleza sigue estando en la dimensión blanda (9ª posición), además de la económica (en la que ocupa también la 12ª posición). En el plano militar, el papel internacional de España es más pasivo (17ª posición).</p><p>En la década de los 90 registró un notable aumento de su presencia global, apoyado en el crecimiento tanto de su dimensión económica como fundamentalmente de su dimensión blanda. Dentro de ésta destaca la variable de turismo, siendo el segundo país con mayor número de visitantes extranjeros.</p><p>Con respecto a la dimensión económica, tras un fuerte crecimiento en los años 2000, venía registrando desde 2012 un descenso continuado de presencia, ligado sobre todo a la reducción de las inversiones y de exportación de servicios, que se recuperan el último año por el crecimiento sostenido del sector turístico.</p><p>Si atendemos a su proyección europea, se fortalece la importancia de la dimensión blanda, con protagonismo de las migraciones, turismo o publicaciones científicas. Por ello, la pérdida de presencia blanda el último año, unido al escaso crecimiento de presencia económica en los últimos años, le hace descender a la 7ª posición por detrás de Italia.</p>'
   WHERE code='ES' AND language='es';

  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Spain maintains its 11th position in the Elcano Global Presence Index, although it has lost some measure of global presence in all of its dimensions (as have the other countries of the region). Spain’s strength continues to be the soft dimension (11th), as well as the economic (also 12th place). However, in the military sphere (17th), Spain’s international role is more passive.</p><p>Spain has recorded a noticeable increase in its global presence since 1990, supported by a steady growth both in its economic and mainly in its soft presence, within which tourism stands out, being the second country in the world with the greatest number of tourist per year.</p><p>Regarding to the economic dimension, after a strong growth in the 2000s, it had been registering a continuous decline since 2012, mainly due to the reduction of investments abroad and the decline in the growth of export of services, which have recovered in the last year pushed by the tourism sector.</p><p>If we look at its European projection, the importance of the soft dimension is strengthened, with a leading role in migration, tourism or scientific publications. Therefore, the loss of soft presence in the EU last year, along with the low growth of economic presence in recent years, makes it descend to the 7th position behind Italy.</p>'
   WHERE code='ES' AND language='en';

  -- Latin America
  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>América Latina se compone de los países de esta región para los que existe cálculo de presencia global. La presencia global del bloque se obtiene mediante la suma de la presencia global de cada país.</p><p>Los países que forman parte de él son Argentina, Bolivia, Brasil, Chile, Colombia, Costa Rica, Cuba, Ecuador, El Salvador, Guatemala, Honduras, México, Panamá, Paraguay, Perú, República Dominicana, Trinidad y Tobago, Uruguay y Venezuela. Representan en conjunto el 96,2% del PIB regional y 95,8% de la población latinoamericana (según datos de 2017 del Banco Mundial).</p>'
   WHERE code='XBLA' AND language='es';

  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Latin America is constituted by the countries in the region whose global presence has been included in the calculation. The bloc’s global presence is obtained by adding the global presence of each country of which it is comprised.</p><p>The countries that make up the bloc are Argentina, Bolivia, Brazil, Chile, Colombia, Costa Rica, Cuba, Ecuador, El Salvador, Guatemala, Honduras, Mexico, Panama, Peru, the Dominican Republic, Trinidad and Tobago, Uruguay and Venezuela. They account for 96.2 % of the Latin America’s GDP and 95.8% of its population (according to World Bank data for 2017).</p>'
   WHERE code='XBLA' AND language='en';

  -- European Union
  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Si considerásemos a la Unión Europea un único país, ocuparía en 2017 el 2º puesto en la clasificación de Presencia Global, por detrás de Estados Unidos. De este modo, tras dos años consecutivos de pérdida de presencia, la Unión Europea cede el primer puesto del ranking. No obstante, sigue siendo mayor su presencia económica -con relevancia de la inversión en el exterior y las exportaciones de servicios- y en algunos indicadores de presencia blanda -turismo, deportes y cooperación al desarrollo-.</p><p>La crisis económica, con especial impacto dentro del espacio comunitario, ha condicionado la presencia de la Unión Europea. Por un lado, ha afectado a los flujos de cooperación internacional, así como al número de inmigrantes recibidos. Por otro lado, desciende su presencia económica, tanto en términos absolutos como en términos relativos, consecuencia la depreciación del euro frente a otras monedas.</p><p>No obstante, tanto la Unión Europea como Estados Unidos mantienen unos elevados niveles de presencia global, que les sitúa por el momento a mucha distancia de China, que ocuparía el tercer lugar.</p>'
   WHERE code='XBEU' AND language='es';

  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>If the European Union were to be considered a single country, it would occupy the 2nd place in the Global Presence ranking in 2017, behind of the United States.</p><p>Thus, after losing presence two consecutive years, the European Union gives the top ranking. However, its economic performance -with relevance of foreign investment and exports of services- and the records in some indicators of the soft presence -such as tourism, sports or development cooperation- are still greater.</p><p>The economic crisis, which has especially hit the European Union, has had an impact on its presence. On the one hand it has led to a drop in international cooperation flows and on the number of immigrants received. On the other, it has slowed down the growth of the economic dimension, influenced by the depreciation of the euro against other currencies.</p><p>However, both the European Union and the United States maintain high levels of global presence, which locates them still far from China, which would occupy the 3rd place.</p>'
   WHERE code='XBEU' AND language='en';

  -- Europe
  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Europa, como bloque, se compone de todos los países que forman parte de la región (sean o no estados miembros de la Unión Europea) para los que existe cálculo de presencia global. La presencia global del bloque se obtiene mediante la mera suma de la presencia global de cada país que conforma el bloque.</p><p>Los países que forman parte del bloque Europa son Alemania, Austria, Azerbaiyán, Bélgica, Bielorrusia, Bulgaria, Chipre, Croacia, Dinamarca, Eslovaquia, Eslovenia, España, Estonia, Finlandia, Francia, Grecia, Hungría, Irlanda, Islandia, Italia, Letonia, Lituania, Luxemburgo, Malta, Noruega, Países Bajos, Polonia, Portugal, Reino Unido, República Checa, Rumanía, Rusia, Serbia, Suecia, Suiza, Turquía y Ucrania.</p><p>Los países europeos considerados para el Índice Elcano de Presencia Global representan el 99,4% del PIB regional y el 97,8% de su población, según datos de 2017 del Banco Mundial.</p>'
   WHERE code='XBE2' AND language='es';

  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Europe, as a bloc, is considered to comprise all the countries in the region (regardless of whether they are member states of the European Union) whose global presence has been calculated. The bloc’s global presence is obtained by adding up the result for each of its constituent countries.
   The countries that make up the European bloc are Austria, Azerbaijan, Belarus, Belgium, Bulgaria, Croatia, Cyprus, the Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Iceland, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, the Netherlands, Norway, Poland, Portugal, Romania, Russia, Serbia, Slovakia, Slovenia, Spain, Sweden, Switzerland, Turkey, the Ukraine and the United Kingdom.</p><p>The European countries considered for the Elcano Global Presence Index account for 99.4% of the region’s GDP and 97.8 % of its population (according to World Bank data for 2017).</p>'
   WHERE code='XBE2' AND language='en';

  -- Asia & Pacific
  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Asia-Pacífico se compone de los países de esta región para los que existe cálculo de presencia global. La presencia global del bloque se obtiene mediante la suma de la presencia global de cada país.</p><p>
   Los países que forman parte de él son Australia, Bangladesh, China, Filipinas, India, Indonesia, Japón, Malasia, Nueva Zelanda, Pakistán, Corea del Sur, Singapur, Tailandia, Vietnam, Myanmar, Sri Lanka, Kazajistán, Turkmenistán y Uzbekistán. Representan el 99,5% y el 96,7% del PIB y de la población de la región, respectivamente (según datos de 2017 del Banco Mundial).</p>'
   WHERE code='XBAP' AND language='es';

  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Asia-Pacific is constituted by the countries in the region for which their global presence has been calculated. The global presence of the bloc is obtained by the pure sum of the global presence of each country that makes up the bloc.</p><p>The countries comprising the bloc are Australia, Bangladesh, China, India, Indonesia, Japan, Malaysia, New Zealand, Pakistan, the Philippines, South Korea, Singapore, Sri Lanka, Thailand, Vietnam, Myanmar, Kazakhstan, Turkmenistan and Uzbekistan. They account for 99.5% and 96.7% of the region’s GDP and population, respectively (according to World Bank data for 2017).</p>'
   WHERE code='XBAP' AND language='en';

  -- Africa Sub.
  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>África Subsahariana se compone de los países de esta región para los que existe cálculo de presencia global; esto es, Angola, Botsuana, Camerún, Costa de Marfil, Etiopía, Kenia, Ghana, Nigeria, República Democrática del Congo, Senegal, Sudáfrica, Sudán, Tanzania, Uganda, Zambia y Zimbabue. La presencia global del bloque se obtiene mediante la suma de la presencia global de cada país.</p><p>Se trata del bloque geográfico menos representativo de los que se incluyen en el Índice puesto que los 16 países considerados representan tan sólo 87% del PIB regional y 73,8% de su población (según datos de 2017 del Banco Mundial).</p>'
   WHERE code='XBSA' AND language='es';

  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Sub-Saharan Africa comprises the countries in the region whose global presence has been calculated: Angola, Botswana, Cameroon, Ivory Coast, Ethiopia, Kenya, Ghana, Nigeria, the Democratic Republic of Congo, Senegal, South Africa, Sudan, Tanzania, Uganda, Zambia and Zimbabwe. The bloc’s global presence is obtained by adding the global presence of each country considered.</p><p>It is the Index’s least representative geographical bloc as 16 countries evaluated account for only 87% of the region’s GDP and 73.8% of its population (according to World Bank 2017 data).</p>'
   WHERE code='XBSA' AND language='en';

  -- Magreb & ME
  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>Magreb y Oriente Medio se compone de los países de esta región para los que existe cálculo de presencia global. La presencia global del bloque se obtiene mediante la suma de la presencia global de cada país.</p><p>Los países que forman parte de él son Arabia Saudí, Argelia, Egipto, Emiratos Árabes Unidos, Irán, Irak, Israel, Jordania, Kuwait, Libia, Líbano, Marruecos, Siria, Omán, Túnez, Qatar y Yemen. Representan el 98% del PIB regional y el 98,5% de su población (según datos de 2017 del Banco Mundial).</p>'
   WHERE code='XBMM' AND language='es';

  UPDATE iepg_data_redux.iepg_comment
   SET comment='<p>The Maghreb and the Middle East are made up of the countries forming the region whose global presence has been calculated. The s global presence is the result of the pure sum of the global presence of each country comprising it. The countries considered are Saudi Arabia, Algeria, Egypt, Iran, Iraq, Israel, Jordan, Kuwait, Libya, Lebanon, Morocco, Syria, Oman, Tunisia, the United Arab Emirates, Qatar and Yemen. They account for 98% of the s GDP and 98.5% of its population (according to World Bank data for 2017).</p>'
   WHERE code='XBMM' AND language='en';

COMMIT;
