
/*
  Update country comments.
*/


BEGIN;
  -- South Korea
  INSERT INTO iepg_data_redux.iepg_comment 
    (code, language, comment, date_in, date_out)
    VALUES
    ('KR', 'es', '<p>La presencia global de Corea del Sur ha aumentado considerablemente desde 1990, alcanzando la undécima posición en el Índice de Presencia Global de 2016 y superando a España en la clasificación. Este hecho ha sido impulsado sobre todo por su presencia blanda –cuya cuota de presencia global se ha casi triplicado desde los 90-, despuntando sobre en lo relativo a tecnología, principal contribución a la presencia blanda coreana, y ciencia.</p><p>En lo relativo a su presencia económica, destacan las exportaciones de manufacturas, donde ocupa la séptima posición a nivel mundial en 2016. Aunque la dimensión económica es la que más contribuye a la presencia global de Corea del Sur –un 53,4% en 2016- es la dimensión en la que menor cuota mundial registra–un 2,1% frente al 2,3% de blanda y el 2,2% de militar-.</p><p>Por otro lado, el aumento de las tensiones con Corea del Norte ha contribuido al incremento sostenido de la presencia militar del país desde 2013. Llama la atención a su vez el despliegue de tropas en el extranjero, que aunque no sea elevado ha pasado de ser nulo en los 90 a 28,7 en 2016, debido en parte a una mayor involucración en las Misiones de Mantenimiento de Paz de la ONU.</p>','2013-01-01', '2013-12-31');

  INSERT INTO iepg_data_redux.iepg_comment 
    (code, language, comment, date_in, date_out)
    VALUES
    ('KR', 'en', '<p>South Korea’s global presence has increased considerably since 1990. It ranks 11th in the 2016 Global Presence Index and has now overtaken Spain. The main driver has been the surge in soft presence –which has more than trebled since the 1990s–, particularly as regards technology, the main contributor in this respect, and science.</p><p>As for economic presence, pride of place goes to exports of manufactured goods, with South Korea being the world’s 7th largest exporter in 2016. Although the economic dimension makes the most significant contribution to the country’s global presence –at 53.4%–, it is the aspect to record the lowest global share –at 2.1%, compared with 2.3% soft presence and 2.2% military presence–.</p><p>Last but not least, the growing tensions with its neighbour, North Korea, have contributed to a sustained increase in South Korea’s military presence since 2013. A notable development is the deployment of troops abroad, which, despite not being high, has risen from zero in the 1990s to 28.7 in 2016, partly due to a greater involvement in UN Peacekeeping Missions.</p>', '2013-01-01', '2013-12-31');

  -- USA
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Desde la caída del bloque soviético, la supremacía estadounidense tiene su visibilidad en distintas esferas del Índice de Presencia Global. En primer lugar, Estados Unidos ocupa el primer puesto de la clasificación en todos los años para los que se calcula y en todas las variables que lo componen, a excepción de las exportaciones de energía. En segundo lugar, registra las mayores cuotas de presencia en todas las dimensiones –21% en la económica; 30,7% en la militar; y 24,7% en la blanda–. Por otro lado, a diferencia del resto de países desarrollados, la dimensión militar mantiene una elevada contribución al valor del Índice –23,2% en 2016–. </p><p>Sin embargo, y al tiempo que mantiene su hegemonía, registra una tendencia de pérdida de presencia en términos relativos y en comparación con el resto de países, –26,5% de cuota en 1990 frente a un 23,8% en 2016–. En un periodo de surgimiento de nuevos actores globales, diversas economías emergentes cosechan ganancias de cuota que reducen el protagonismo estadounidense, donde destaca el auge de países petroleros y asiáticos. Sin embargo, la desaceleración del proceso de globalización en los últimos años ha producido una ligera reconcentración de la presencia global, permitiendo a EEUU mantener su cuota de presencia en los últimos años.</p><p>Esta tendencia se debe fundamentalmente a la dimensión económica del Índice, donde a pesar de ser el principal motor de la globalización, y por tanto la dimensión en la que Estados Unidos registra mayores aumentos de presencia –especialmente en las exportaciones de servicios y stock de inversión–, reduce su cuota en casi tres puntos porcentuales desde 1990. La recuperación desde entonces de su cuota económica ha permitido compensar las pérdidas en la dimensión blanda. Al mismo tiempo, la tendencia general a la desmilitarización de la presencia de los países en el mundo permite a Estados Unidos mantener su hegemonía militar a pesar de la reducción del número de unidades desplegadas.</p>'
    WHERE code='US' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>US supremacy since the fall of the Soviet bloc is evident in various aspects of the Global Presence Index. First, it has ranked 1st in all years and in all variables, except in exports of energy goods. Secondly, it has the highest share of presence in all dimensions: 21% in economic, 30.7% in military and 24.7% in soft presence. Moreover, unlike other developed countries, its military dimension continues to make a significant contribution to the Index’s vale, at 23.2% in 2016. </p><p>However, while maintaining its hegemony, the US presence has declined in relative terms and in comparison with other countries, from a 26.5% share in 1990 to 23.8% in 2016. In a period of emergence of new global players, several economies reap gains of share that reduce the American role, where highlights the rise of Asian and oil exporter countries. This trend is mainly due to the Index’s economic dimension, which despite being the one in which the US has recorded the largest increase –especially in the export of primary goods, services and stock of investment– has reduced its contribution by almost three percentage points since 1990.</p><p>Meanwhile, the general trend in most countries of demilitarizing their presence has allowed the US to maintain its military hegemony despite the reduction in the number of units it has deployed. Nevertheless, the slowing down of the globalization process over the last couple of years has resulted in a mild re-concentration of global presence, allowing the US to maintain its global presence share.</p>'
    WHERE code='US' AND language='en';

  -- China
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>El notable ascenso del gigante asiático en las últimas décadas tiene su reflejo en la clasificación del Índice de Presencia Global, donde escala diez posiciones desde 1990. Este crecimiento se da en paralelo al registrado en términos de PIB, otorgando el protagonismo del auge chino a la dimensión económica –en 1990 ocupaba el 17º lugar frente al 2º en 2016 en el ranking de presencia económica–, impulsado por el crecimiento de las exportaciones manufactureras, pero también de bienes primarios y servicios. Por ello, la naturaleza de su presencia global es principalmente económica, con un peso del 62,6% sobre el valor índice en 2016. Sin embargo, registra también recientes mejoras sustanciales en variables de la dimensión blanda –en turismo, deportes, ciencia, información y tecnología-, mostrando una posible tendencia de modificación de las bases de su presencia, a la vez que consolida su posición global. Esta consolidación se evidencia con el incremento de cuota de presencia –un 7,1% en 2016 frente al 1,6% de 1990– que, si bien se sitúa todavía lejos de los registros estadounidenses, le ha permitido adelantar a las potencias europeas, Francia, Reino Unido y Alemania, y situarse en el segundo puesto del ranking de presencia global.</p>'
    WHERE code='CN' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>China’s remarkable rise in recent decades is reflected in its classification in the Global Presence Index, where it has risen 10 positions since 1990. It has also grown in terms of GDP, with a prime role played by the economic presence –in 1990 China ranked 17th and in 2016 the country holds 2nd place in this dimension– mainly driven by the export of manufactures, but also of primary goods and services. Hence, the nature of its global presence is mainly economic, accounting for 62.6% of the Index’s value in 2016. However, there has been a recent improvement in the soft variables –tourism, sports, science, information and technology–, reflecting a possible change in trend in the nature of China’s presence, while it has consolidated its global position. This is also evident in terms of share, at 7.1% in 2016 compared with 1.6% in 1990. Although still far from the US, China has recently overtaken France, the United Kingdom and Germany.</p>'
    WHERE code='CN' AND language='en';

  -- Germany
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>A pesar del crecimiento de presencia respecto del año anterior, Alemania se mantiene en la tercera posición del ranking, a la que quedó relegada en 2014, siendo superado en presencia global por China. Desde mediados de los 90, tras la reunificación y la caída del bloque soviético, Alemania registró un aumento continuado de presencia económica, dimensión que más valor le aporta y donde, a excepción de las exportaciones energéticas, ocupa lugar destacado en todas las variables a nivel mundial. Sin embargo, el descenso de presencia registrado en 2013 y el modesto crecimiento de los últimos años, no le han permitido mantener una segunda posición que ocupaba desde el año 2000. Dentro de la Unión Europea, Alemania mantiene su hegemonía. A pesar de la contracción de la demanda de los socios comunitarios, con descensos de las exportaciones de manufacturas con destino al mercado europeo, la presencia europea alemana tiene un carácter fundamentalmente económico, destacando el stock de inversión y las exportaciones de manufacturas y servicios. No obstante, en 2014 registra por primera vez una pérdida en términos absolutos de presencia económica dentro de la UE. Dentro de la dimensión blanda, la presencia alemana se caracteriza por apoyarse en pilares sólidos, como las variables de información, tecnología y ciencia.</p>'
    WHERE code='DE' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Despite the growth of its global presence in absolute terms, Germany remains at 3rd place in the global presence ranking -spot to which the country was relegated in 2014-, being overtaken in global presence by China. Since the mid-1990s, and following the fall of the Soviet Union and reunification, Germany has been recording a steady growth in its economic presence, the dimension that provides the highest contribution to its position and in which it occupies a prominent place in all variables –save energy exports–. The decline of presence in 2013 and the slight recovery over the past years have not allowed Germany to maintain the 2nd position in the global presence ranking (held since the year 2000). Within the European Union, Germany has maintained its hegemony. Despite the decreasing demand from its European Union partners, Germany’s European presence has an essentially economic nature, based on its investment stock and services and manufacturing exports. Nevertheless, in 2014 Germany registers for the first time an economic presence loss in absolute terms within the EU. Furthermore, within the soft dimension, its presence is based on the solid pillars of information, technology and science.</p>'
    WHERE code='DE' AND language='en';

  -- UK
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>La presencia global de Reino Unido ha registrado un constante aumento desde 1990, lo que le ha permitido ascender posiciones en la clasificación, superando a Japón y a Francia hasta 2015 y estando igualado con este último país en 2016. En 2015, la presencia global británica decrece en términos absolutos, quedando relegado al cuarto puesto mundial, por detrás de Alemania, a quien adelantó en 2014, posición que mantiene en 2016 a pesar de un ligero repunte. Se trata de una presencia principalmente blanda –donde destacan los valores alcanzados en información, cultura y desarrollo–, siendo el país europeo con mayor presencia en esta dimensión, lo que le ha permitido mantener su cuota global a pesar del ascenso de países emergentes. La posición relativa internacional de Reino Unido se sostiene, además, en las exportaciones de servicios e inversión –téngase en cuenta la importancia de los servicios bancarios, seguros, consultoría y asesoría, así como su función de hub financiero-. El decrecimiento del valor absoluto y relativo al que asiste Reino Unido desde 2015 responde a la moderación de los valores económicos y globales tras su extraordinario crecimiento en 2014, cuando el incremento puntual de las ventas de oro provocó un fuerte crecimiento en las exportaciones de bienes primarios.</p><p>Dentro del espacio comunitario, Reino Unido mantiene la segunda posición en 2016 en presencia europea. No obstante, la brecha respecto a Alemania persiste, mientras que Francia se mantiene todavía lejos. Esto podría ser signo del fortalecimiento de relaciones extracomunitarias del Reino Unido en un contexto de menor crecimiento en Europa. Además, mantiene una tendencia de reducción de presencia económica a favor de la dimensión blanda –donde tienen protagonismo los deportes, información y cultura, y también, aunque perdiendo relevancia, la ciencia y la educación–, siendo desde 2015 el país con mayor presencia blanda en la región.</p>'
    WHERE code='GB' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>The United Kingdom’s global presence has steadily increased since 1990, climbing up the ranking to outstrip France and Japan until 2015 and being tied with the latter country in 2016. In 2015 British global presence decreased in absolute terms and the country fell to the fourth place in the global presence ranking -behind Germany, the country it overtook in 2014-, holding on to the same position in 2016 despite registering a slight increase. Its presence is of a soft nature –with high marks in information, culture and development– and it is the European country with the largest presence in this dimension, allowing it to keep its global share despite the rise of emerging countries. However, its increase of presence has been sustained mainly by its economic dimension with prominence of investment stock and services exports –based on the importance of banking, insurance and consultancy and advisory services as well as its role as a financial hub–. The recent contraction of the United Kingdom’s absolute and relative values were caused by the moderation of its economic and global values growth rate after their extraordinary peak in 2014, when an increase of international gold sales caused a sharp growth in the country’s primary good exports.</p><p>Within the European Union, the United Kingdom keeps the 2nd place in 2016 in European presence. Accordingly, the gap with respect Germany has increased, while it still leaves France further behind. That could be a symptom of the United Kingdom’s strategy of deepening its extra-European Union relations in a context of slow-growing Europe. Its economic presence is on a downward trend relative to the soft dimension –in which sports, information, culture, and also, although to a lesser degree, in science and education play a significant role–, being since 2015 the country with more soft presence in the region.</p>'
    WHERE code='GB' AND language='en';

  -- Rusia
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>La evolución de la presencia global de Rusia puede dividirse en dos periodos. El primero, que abarcaría la década de los 90, caracterizado por una drástica reducción del valor del Índice tras la caída del bloque soviético, con un sustancial descenso de presencia militar, y en menor medida, en la blanda. Así, en 1990 la dimensión militar sostenía de manera abrumadora la presencia global de la entonces Unión Soviética, con un peso del 84,5% del valor total. En el segundo periodo, a partir del año 2000, comienza un proceso de recuperación de presencia en el mundo apoyado principalmente en su dimensión económica que, sin embargo, no le permite alcanzar los mismos niveles que obtenía durante la época soviética hasta 2012. Su condición de primer exportador de gas y segundo de petróleo a nivel mundial hace que sean las exportaciones de bienes energéticos el motor principal de su presencia económica, aportando un 11,7% al valor de su Índice en 2016. Su presencia blanda ha disminuido en términos absolutos, indicador donde mantiene una posición baja en todas las variables a excepción de deportes, debido a su éxito en el medallero olímpico y migraciones, siendo el segundo país receptor del Índice.</p>'
    WHERE code='RU' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>The evolution of Russia’s global presence can be divided into two periods. The first, during the 1990s, was characterized by a drastic reduction in its Index value following the fall of the Soviet bloc, with a substantial decrease in military presence. In 1990 the military dimension largely underpinned the Soviet Union’s global presence, with a weight of 84.5% in its total value. In the second period, from 2000 onwards, there has been a steady process of recovery in its global presence, primarily supported by the economic dimension, although Russia has been unable to return to the levels of the Soviet era until 2012. As the leading gas exporter and the second-largest oil exporter, energy goods are mainly responsible for the increase, contributing 11.7% to the Index’s value in 2016. Russia’s soft presence has decreased in global terms, and it is still occupying a very low position in all variables, with the exception of sports –given its success in the Olympic medal table– and migrations –being the second-largest host country worldwide–.</p>'
    WHERE code='RU' AND language='en';

  -- France
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>A pesar del aumento continuado de presencia global, Francia se enfrenta a una pérdida progresiva de relevancia en la escena internacional. Ello se refleja en su posición en el ranking de presencia global, la cuarta desde los 90. Mantiene un perfil similar al de otras economías europeas, esto es, elevados registros de presencia blanda –sobre todo en turismo, siendo la primera potencia turística a nivel mundial-; al mismo tiempo, su dimensión económica crece, aunque en menor cuantía y con ciertas variaciones, debidas en parte a la crisis que atraviesa la región.</p><p>En términos europeos, se sitúa como la tercera economía con mayor presencia dentro del espacio comunitario, pero con un perfil contrario al constatado en términos globales. Las variables económicas tienen mayor relevancia –donde destacan también las exportaciones de servicios y el stock de inversión- y han sido las que han sostenido el aumento de la presencia europea del país.</p>'
    WHERE code='FR' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Despite its continued increase in global presence, France faces a progressive loss of relevance in the international scene. This is reflected in the decline in its share of presence and its loss of position in the ranking, holding on to the fourth position since the 90s. France maintains a profile that is similar to those of other European economies, with a high soft presence –being the leading worldwide tourist destination–, while the economic dimension grows, yet in short amount and with certain variations, due to the European economic crisis.</p><p>In European terms, France ranks 3rd but with the opposite profile than it has in global terms. Its economic variables are more important –registering high marks in stock investments and exports of services-, which has allowed the country to steadily increase its European global presence.</p>'
    WHERE code='FR' AND language='en';

  -- Japan
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Japón ocupa el 6º lugar en la clasificación, adelantando una posición con respecto a 2015 y a pesar del letargo económico tras la crisis de los 90 que le ha hecho registrar, por lo general, menores tasas de crecimiento de presencia que países que le acompañan en los principales puestos. A pesar de mantener el tercer PIB más elevado a nivel mundial, en términos de presencia, la economía nipona ha sufrido una importante pérdida de relevancia económica, pasando de ocupar el 4º puesto en esta dimensión en 1990, al 9º desde el 2015. Se observa lo mismo en términos de cuota de presencia económica, que pasa de un 7,4% en los 90 a un 4,3% en 2016. No obstante, mantiene elevados registros de presencia blanda –5º puesto mundial en esta dimensión en 2016–, sustentados en las variables de tecnología, ciencia y cooperación al desarrollo. Cabe añadir que, a pesar de la desmilitarización sufrida tras la Segunda Guerra Mundial, la dimensión militar mantiene una contribución estable a la presencia japonesa -15,5% en 2016– y superior a otras economías desarrolladas. Estos resultados agudizan la tendencia de pérdida de cuota global que venía registrando el país desde 1990 –del 5,7% de entonces al 4,5% de 2016-. </p>'
    WHERE code='JP' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Japan ranks 6th despite its economic lethargy following the crisis of the 1990s, which led to it recording lower growth rates in its presence than other major countries. Despite retaining the 3rd largest GDP, Japan has suffered a significant decline in economic presence, falling from the 4th position in 1990 to 9th since 2015. The same can be observed in the case of its economic presence, whose share was 7.4% in the 90s and has reached 4.3% in 2016. However, it still has a high score in soft presence –being 5th worldwide– supported by technology, science and cooperation. At the same time, and despite its demilitarization after WWII, the military dimension contributes in 15.5% to the country’s global presence, higher than for other developed economies. This heightens the downward trend in terms of share, dropping from 5.7% in 1990 to 4.5% in 2016.</p>'
    WHERE code='JP' AND language='en';

  -- Netherlands
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>A pesar del paulatino descenso de los Países Bajos en la clasificación mundial según Producto Interior Bruto, el país se mantiene en puestos elevados del Índice de Presencia Global. Se trata de una presencia de naturaleza fundamentalmente económica –esta dimensión representa en 2016 el 77,3% de su presencia global–. Es el quinto exportador mundial de bienes primarios y el principal exportador europeo de energía, donde a su condición de principal productor europeo y poseedor de importantes yacimientos de gas, se le une la posición estratégica del puerto de Rotterdam. Así, buena parte de su elevado registro puede explicarse por su condición de hub exportador.</p><p>Al igual que otras economías europeas, la crisis ha tenido incidencia negativa en muchas variables, y en la economía neerlandesa dada su condición de exportador energético se añade el impacto del descenso de los precios del petróleo en la reducción del valor de sus exportaciones.</p><p>Este perfil se repite en el análisis de su presencia dentro del espacio europeo, donde ocupa el cuarto puesto por detrás de Alemania, Francia y Reino Unido, aunque con escasa relevancia en la dimensión blanda. Sin embargo, los Países Bajos registran en 2016 una nueva pérdida de presencia en Europa, debido tanto a la dimensión económica como a la blanda.</p>'
    WHERE code='NL' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Despite the gradual decline in its world ranking by GDP, the Netherlands retains a high position in the Global Presence Index. Its economic dimension –which in 2016 accounted for 77.3% of its total value– continues to be the most important component. It is the 5th largest exporter of primary goods and Europe’s leading exporter of energy, adding to its condition as the leading European producer and owner of major gas fields its possession of the strategic port of Rotterdam. Thus, much of its position can be explained by its role as an export hub. Like other European economies, the crisis has had an impact on many variables, and giving its condition of energy exporter, Netherlands has also suffered from the decline of oil prices in the international market, reducing the value of its exports. </p><p>Its profile is replicated in Europe, where The Netherlands has the 4th highest value after Germany, France and the United Kingdom, despite the small relevance of its soft presence. The Netherlands records a new loss of European presence, mainly due to its economic and soft presence.</p>'
    WHERE code='NL' AND language='en';

  -- Canada
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Canadá se mantiene en los principales puestos de la clasificación del Índice de Presencia Global, a pesar de la reducción relativa de su peso económico –pierde cinco puestos en la clasificación mundial de PIB desde 1990- y del auge de China. Cuarto productor de gas y petróleo a nivel mundial (según el informe “BP Statistical Review of World Energy” de 2016), las exportaciones de bienes primarios y energéticos constituyen la principal contribución a la presencia global canadiense en 2016. Por este motivo la presencia de Canadá es fundamentalmente económica –68,22% de su presencia–, aunque mantiene, como otras economías desarrolladas, elevados registros en la dimensión blanda y casi nula en la militar.</p>'
    WHERE code='CA' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Canada remains in the top positions of the Global Presence Index, despite its loss of economic weight –down five positions since 1990– and the rise of China, which have pushed it down one position in the global presence ranking. Being the 4th largest gas and oil producer (according to the BP Statistical Review of World Energy of 2016), the exports of energy and primary goods were the main contributors to Canada’s global presence. For this reason, Canada’s presence is fundamentally economic –accounting for 68.22% of its global presence– while it retains, similarly to other developed economies, a high score in the soft dimension and an almost nil presence in the military one.</p>'
    WHERE code='CA' AND language='en';

  -- Italy
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>A pesar de perder progresivamente posiciones tanto en términos de cuota de presencia global como de PIB, Italia se mantiene, desde 2010, en el 11º puesto del ranking. Esta tendencia se debe a la ralentización del crecimiento de su presencia económica, dimensión en la que ocupa el 11º puesto a nivel mundial frente al 7º de 1990. No obstante, continúa siendo uno de los ocho países más industrializados, por lo que su presencia económica es elevada, apoyada en las exportaciones de manufacturas e inversiones. Al igual que ocurre con otras potencias europeas, mantiene registros elevados en la dimensión blanda –apoyada en tecnología, ciencia y turismo– donde el descenso de los flujos de cooperación internacional ha contribuido a la inédita reducción del valor del índice en términos absolutos desde 2013.</p><p>Por el contrario, dentro del espacio europeo su presencia es fundamentalmente blanda –estando entre los cinco primeros puestos en turismo, migraciones, tecnología y ciencia, y entre los diez primeros en deportes e información– y ha sido precisamente esta dimensión la que mayores crecimientos ha registrado. No obstante, son insuficientes para mantener su posición frente a España, por lo que desciende a la séptima posición en términos de presencia europea principalmente por su descenso de presencia económica. La caída, en 2014, de su valor absoluto de presencia europea parece revertirse a partir de 2015, pero es insuficiente para subir de posición en el orden europeo.</p>'
    WHERE code='IT' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Despite its steady loss of both positions and share in terms of Global Presence and GDP, Italy holds the eleventh place in the Global Presence Index ranking since 2010. This trend is due to the slower growth of its economic presence, in which it ranked 11th in 2016, compared with 7th in the 1990s. However, Italy is still one of the eight most heavily industrialized countries, so its presence is fundamentally economic, supported by manufactured exports –despite a slight decline in 2016- and investments. Similarly to other European countries, Italy has a high score in the soft dimension –mainly because of technology, science and tourism–, where the reduction in international cooperation flows contributed to an unprecedented decline in the Index in absolute terms in 2013.</p><p>Within the European Union, Italy’s presence is of a soft nature. This dimension has registered the greatest grown –climbing positions up to being one of the top five European countries in tourism, migration technology and science and one of the top ten in sports and information–. Nevertheless, this has been insufficient for Italy to maintain its position relative to Spain, dropping to 7th place in terms of European presence mainly because of the loss of economic presence. Actually, in 2014, Italy has lost European presence in absolute terms for the first time in our series, though the trend seems to be reverting as of 2015, yet not enough to help Italy climb in the regional ranking.</p>'
    WHERE code='IT' AND language='en';

  -- Spain
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>España ha registrado un notable aumento de su presencia global desde 1990, apoyado en el crecimiento de su dimensión blanda. Dentro de esta destaca la variable de turismo, siendo el segundo país con mayor número de visitantes extranjeros solo por detrás de Estados Unidos.</p><p>Con respecto a la dimensión económica, desde 2012 viene registrando un ligero descenso de presencia, ligado sobre todo a la reducción de las inversiones y de exportación de servicios–.</p><p>Más aún, en 2011 se reduce por primera vez el valor del Índice de España, evidenciando el impacto de la crisis en términos de presencia global.</p><p>Desde 2014 España ha venido registrando una pérdida de cuota de presencia europea en términos absolutos, motivada por el descenso de la presencia económica, uniéndose a una tendencia registrada por varios socios comunitarios. Sin embargo, esta tendencia se ha revertido en 2016, ganando cuota de presencia europea, empujada por el mayor dinamismo de la dimensión blanda –migraciones y turismo- que cobra cada vez más protagonismo frente a la económica.</p>'
    WHERE code='ES' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Spain has recorded a noticeable increase in its global presence since 1990, supported by a steady growth in its soft presence, within which tourism stands out, being the second country in the world with the greatest number of tourist per year, behind the United States. However, Spain has registered a slowdown of its economic presence since 2012, due to a drop in investments and exports of services. Moreover, since 2011 Spain registers for the first time a reduction of its presence, which means that the European crisis has had an impact on the Spanish global presence.</p><p>Since 2014, Spain has suffered a decline of its European presence in absolute terms, driven by a decline in its economic dimension, joining the trend followed by other European countries. Nevertheless this trend seems to have changed in 2016, year in which Spain gains European presence quote, driven by a greater dynamism of its soft presence –migrations and tourism-, which is becoming increasingly important compared to its economic dimension.</p>'
    WHERE code='ES' AND language='en';

  -- Latin America
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>América Latina se compone de los países de esta región para los que existe cálculo de presencia global. La presencia global del bloque se obtiene mediante la suma de la presencia global de cada país.
    Los países que forman parte de él son Argentina, Bolivia, Brasil, Chile, Colombia, Costa Rica, Guatemala, México, Perú, República Dominicana, Uruguay y Venezuela. Representan en conjunto el 96,9% del PIB regional y 92,9% de la población latinoamericana (según datos de 2016 del Banco Mundial).</p>'
    WHERE code='XBLA' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Latin America is constituted by the countries in the region whose global presence has been included in the calculation. The bloc’s global presence is obtained by adding the global presence of each country of which it is comprised.
    The countries that make up the bloc are Argentina, Bolivia, Brazil, Chile, Colombia, Costa Rica, Guatemala, Mexico, Peru, the Dominican Republic, Uruguay and Venezuela. They account for 96.9 % of the Latin America’s GDP and 92.9% of its population (according to World Bank data for 2016).</p>'
    WHERE code='XBLA' AND language='en';

  -- Europe
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Europa, como bloque, se compone de todos los países que forman parte de la región (sean o no estados miembros de la Unión Europea) para los que existe cálculo de presencia global. La presencia global del bloque se obtiene mediante la mera suma de la presencia global de cada país que conforma el bloque.
    Los países que forman parte del bloque Europa son Alemania, Austria, Azerbaiyán, Bélgica, Bielorrusia, Bulgaria, Chipre, Croacia, Dinamarca, Eslovaquia, Eslovenia, España, Estonia, Finlandia, Francia, Grecia, Hungría, Irlanda, Islandia, Italia, Letonia, Lituania, Luxemburgo, Malta, Noruega, Países Bajos, Polonia, Portugal, Reino Unido, República Checa, Rumanía, Rusia, Serbia, Suecia, Suiza, Turquía y Ucrania.
    Los países europeos considerados para el índice Elcano de presencia global representan el 99,5% del PIB regional y el 97,4% de su población, según datos de 2016 del Banco Mundial.</p>'
    WHERE code='XBE2' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Europe, as a bloc, is considered to comprise all the countries in the region (regardless of whether they are member states of the European Union) whose global presence has been calculated. The bloc’s global presence is obtained by adding up the result for each of its constituent countries.
    The countries that make up the European bloc are Austria, Azerbaijan, Belarus, Belgium, Bulgaria, Croatia, Cyprus, the Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Iceland, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, the Netherlands, Norway, Poland, Portugal, Romania, Russia, Serbia, Slovakia, Slovenia, Spain, Sweden, Switzerland, Turkey, the Ukraine and the United Kingdom.
    The European countries considered for the Elcano Global Presence Index account for 99.5% of the region’s GDP and 97.4 % of its population (according to World Bank data for 2016).</p>'
    WHERE code='XBE2' AND language='en';

  -- Asia & Pacific
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Asia-Pacífico se compone de los países de esta región para los que existe cálculo de presencia global. La presencia global del bloque se obtiene mediante la suma de la presencia global de cada país.
    Los países que forman parte de él son Australia, Bangladesh, China, Filipinas, India, Indonesia, Japón, Malasia, Nueva Zelanda, Pakistán, República de Corea, Singapur, Tailandia, Vietnam, Myanmar, Sri Lanka, Kazajistán, Turkmenistán y Uzbekistán. Representan el 99,5% y el 96,6% del PIB y de la población de la región, respectivamente (según datos de 2016 del Banco Mundial).</p>'
    WHERE code='XBAP' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Asia-Pacific is constituted by the countries in the region for which their global presence has been calculated. The global presence of the bloc is obtained by the pure sum of the global presence of each country that makes up the bloc.
    The countries comprising the bloc are Australia, Bangladesh, China, India, Indonesia, Japan, Malaysia, New Zealand, Pakistan, the Philippines, the Republic of Korea, Singapore, Sri Lanka, Thailand, Vietnam, Myanmar, Kazakhstan, Turkmenistan and Uzbekistan. They account for 99.5% and 96.6% of the region’s GDP and population, respectively (according to World Bank data for 2016).</p>'
    WHERE code='XBAP' AND language='en';

  -- Africa Sub.
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>África Subsahariana se compone de los países de esta región para los que existe cálculo de presencia global; esto es, Angola, Costa de Marfil, Etiopía, Kenia, Ghana, Nigeria, República Democrática de Congo, Sudáfrica, Sudán, y Tanzania. La presencia global del bloque se obtiene mediante la suma de la presencia global de cada país.
    Se trata del bloque geográfico menos representativo de los que se incluyen en el índice puesto que los siete países considerados representan tan sólo 79,7% del PIB regional y 59% de su población (según datos de 2016 del Banco Mundial).</p>'
    WHERE code='XBSA' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Sub-Saharan Africa comprises the countries in the region whose global presence has been calculated: Angola, Ivory Coast, Ethiopia, Kenya, Ghana, Nigeria, the Democratic Republic of Congo, South Africa, Sudan, and Tanzania The bloc’s global presence is obtained by adding the global presence of each country considered.
    It is the Index’s least representative geographical bloc as the seven countries evaluated account for only 79.7% of the region’s GDP and 59% of its population (according to World Bank 2016 data).</p>'
    WHERE code='XBSA' AND language='en';

  -- Magreb & ME
  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>Magreb y Oriente Medio se compone de los países de esta región para los que existe cálculo de presencia global. La presencia global del bloque se obtiene mediante la suma de la presencia global de cada país.
    Los países que forman parte de él son Arabia Saudí, Argelia, Egipto, Emiratos Árabes Unidos, Irán, Iraq, Israel, Jordania, Kuwait, Libia, Líbano, Marruecos, Siria, Omán, Túnez, Qatar y Yemen. Representan el 98,3 % del PIB regional (según datos de 2016 del Banco Mundial) y el 98,6% de su población, tomando la misma fuente.</p>'
    WHERE code='XBMM' AND language='es';

  UPDATE iepg_data_redux.iepg_comment 
    SET comment='<p>The Maghreb and the Middle East are made up of the countries forming the region whose global presence has been calculated. The bloc’s global presence is the result of the pure sum of the global presence of each country comprising it. The countries considered are Saudi Arabia, Algeria, Egypt, Iran, Iraq, Israel, Jordan, Kuwait, Libyan Arab Jamahiriya, Lebanon, Morocco, Syria, Oman, Tunisia, Qatar and Yemen. They account for 98.3% of the region’s GDP and 98% of its population (according to World Bank data for 2016).</p>'
    WHERE code='XBMM' AND language='en';

COMMIT;

